// 飞书多维表格插件实例 ID 常量
export const APP_BITABLE_APP_TOKEN = 'Kgy0b4bvmaJSK8sjQDscUrNJnOf';
export const WEB_BITABLE_APP_TOKEN = 'EX4RbTvp9agYNws6PIHcKD20nqf';

export const BITABLE_INSTANCES = {
  workbench: 'feishu_bitable_01_buried_point_design_workbench_1',
  paramDetail: 'feishu_bitable_design_parameter_detail_1',
  qualityGate: 'feishu_bitable_background_publish_quality_access_control_read_1',
  lifecycle: 'feishu_bitable_buried_point_lifecycle_read_1',
  queryLibrary: 'feishu_bitable_app_buried_point_readonly_1',
  officialParamDetail: 'feishu_bitable_app_parameter_detail_1',
  webWorkbench: 'feishu_bitable_web_tracking_design_workbench_1',
  webParamDetail: 'feishu_bitable_web_design_parameter_detail_1',
  webQueryLibrary: 'feishu_bitable_web_tracking_query_library_1',
  webOfficialParamDetail: 'feishu_bitable_web_parameter_detail_1',
} as const;

export type BitableInstanceKey = keyof typeof BITABLE_INSTANCES;

export const BITABLE_APP_TOKENS: Record<BitableInstanceKey, string> = {
  workbench: APP_BITABLE_APP_TOKEN,
  paramDetail: APP_BITABLE_APP_TOKEN,
  qualityGate: APP_BITABLE_APP_TOKEN,
  lifecycle: APP_BITABLE_APP_TOKEN,
  queryLibrary: APP_BITABLE_APP_TOKEN,
  officialParamDetail: APP_BITABLE_APP_TOKEN,
  webWorkbench: WEB_BITABLE_APP_TOKEN,
  webParamDetail: WEB_BITABLE_APP_TOKEN,
  webQueryLibrary: WEB_BITABLE_APP_TOKEN,
  webOfficialParamDetail: WEB_BITABLE_APP_TOKEN,
};

// 表 ID 映射
export const BITABLE_TABLE_IDS: Record<BitableInstanceKey, string> = {
  workbench: 'tblqHhr5aZwr4QOZ',
  paramDetail: 'tblesT69TDCUKzhs',
  qualityGate: 'tblUCH6PxC1sQwXx',
  lifecycle: 'tblJ8G3X1001g9oA',
  queryLibrary: 'tblAhScEFQYAJC2g',
  officialParamDetail: 'tblEYv9lGZeenbT2',
  webWorkbench: 'tblsFFvYkTPkabFT',
  webParamDetail: 'tblMaw89yVi68YY6',
  webQueryLibrary: 'tbly7VI4kwFz5qwR',
  webOfficialParamDetail: 'tblNAMKr5S38iXJQ',
};

interface BitableFieldConfig {
  id: string;
  name: string;
  type: number;
  bizType: string;
  readable: boolean;
  writeable: boolean;
  enumValues?: string[];
}

export const BITABLE_FIELDS: Record<BitableInstanceKey, BitableFieldConfig[]> = {
  workbench: [
    {
      id: 'fldg05KBjv',
      name: '需求ID',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldsrxaEFF',
      name: 'evt_id',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldUCSjKe9',
      name: '事件中文名',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'flda01x39h',
      name: '流程阶段',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldvW2Mwmt',
      name: '优先级',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldDE3SD4L',
      name: '端',
      type: 4,
      bizType: 'MultiSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldgwGzNsP',
      name: '需求提出人',
      type: 11,
      bizType: 'User',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldOXTa5uB',
      name: '需求录入人',
      type: 11,
      bizType: 'User',
      readable: true,
      writeable: true,
    },
    {
      id: 'flddP9xaKr',
      name: '数据负责人',
      type: 11,
      bizType: 'User',
      readable: true,
      writeable: true,
    },
    {
      id: 'flduVUwRRe',
      name: '研发负责人',
      type: 11,
      bizType: 'User',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldy1MVSYO',
      name: 'DS验收人',
      type: 11,
      bizType: 'User',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld1Idvjsh',
      name: '创建时间',
      type: 1001,
      bizType: 'CreatedTime',
      readable: true,
      writeable: false,
    },
    {
      id: 'fldqOMbbdw',
      name: '评审状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldRUa4hOE',
      name: '埋点开发状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldBEJ4bPe',
      name: 'DS验收状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldWc2ndH9',
      name: 'DS验收证据',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldb2kDxmo',
      name: 'DS验收时间',
      type: 5,
      bizType: 'DateTime',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldvE12B7Q',
      name: '发布状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldlZtkX1F',
      name: '发布错误',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'flddzY8JU3',
      name: '发布门禁状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldhtsSfX3',
      name: '发布时间',
      type: 5,
      bizType: 'DateTime',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldUp9uyOX',
      name: '版本',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldWEscUBI',
      name: '最低版本',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldIY1kz1U',
      name: '一级分类',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld2CdL7yh',
      name: '记录类型',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldS1hupWM',
      name: '变更类型',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldJdHUCCZ',
      name: '处理方',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld840ujbb',
      name: '需求背景',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldhGa3ry1',
      name: '事件定义',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld6EFFRiW',
      name: '触发时机',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld6yxssk2',
      name: 'UI图',
      type: 17,
      bizType: 'Attachment',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld4AVmBKx',
      name: '指标/使用场景',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldMlUIhg9',
      name: '公共属性要求',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld3tWUeqF',
      name: '需求链接',
      type: 15,
      bizType: 'Url',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldrV4iCGt',
      name: '参数明细入口',
      type: 15,
      bizType: 'Url',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldMPppwVN',
      name: '参数拆行状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld1zCxhGT',
      name: '关联参数明细（系统）',
      type: 18,
      bizType: 'DuplexLink',
      readable: true,
      writeable: false,
    },
    {
      id: 'fldj9UY9sV',
      name: '生命周期记录',
      type: 18,
      bizType: 'DuplexLink',
      readable: true,
      writeable: false,
    },
    {
      id: 'fld8SZSD5Q',
      name: '发布质量门禁',
      type: 18,
      bizType: 'DuplexLink',
      readable: true,
      writeable: false,
    },
    {
      id: 'fldgyxhfbq',
      name: '评审意见',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldEcYYBzj',
      name: '发布门禁失败原因',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldIf6WnY9',
      name: '指标映射',
      type: 18,
      bizType: 'DuplexLink',
      readable: true,
      writeable: false,
    },
    {
      id: 'fldayFBZFq',
      name: '正式状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'flduQb8f0G',
      name: '上线监控状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldj7cAR2N',
      name: '上线监控结论',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldks1ggnG',
      name: '稳定归档时间',
      type: 5,
      bizType: 'DateTime',
      readable: true,
      writeable: true,
    },
  ],
  paramDetail: [
    {
      id: 'fldZ5kcKld',
      name: '设计参数主键',
      type: 20,
      bizType: 'Formula',
      readable: true,
      writeable: false,
    },
    {
      id: 'fldWR3XMpR',
      name: 'evt_id',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldKMQGhZb',
      name: '参数名',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldYikrhVb',
      name: '数据类型',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldK4NfHfC',
      name: '参数定义',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldLgmr3Fs',
      name: '必传规则',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldztDDZ4W',
      name: '枚举/取值范围',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldSheG80P',
      name: '默认值/示例',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldZyCy2Iv',
      name: '参数状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldJtB34PK',
      name: '版本',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldepHtsWx',
      name: '变更类型',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldtJMMilx',
      name: 'App适用性',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldVqnDJBr',
      name: '评审状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldTuD8968',
      name: '发布状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldJcTZyE5',
      name: '条件说明',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldGIZOLH4',
      name: '来源设计记录ID',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldGAMGK6Q',
      name: '关联设计',
      type: 18,
      bizType: 'DuplexLink',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld49ifSgi',
      name: '创建时间',
      type: 1001,
      bizType: 'CreatedTime',
      readable: true,
      writeable: false,
    },
    {
      id: 'fldbcmpC28',
      name: '更新时间',
      type: 1002,
      bizType: 'ModifiedTime',
      readable: true,
      writeable: false,
    },
  ],
  qualityGate: [
    {
      id: 'fldevt_id',
      name: 'evt_id',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: false,
    },
    {
      id: 'fldgate_item',
      name: '门禁项',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: false,
    },
    {
      id: 'fldgate_result',
      name: '门禁结果',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: false,
    },
    {
      id: 'fldgate_detail',
      name: '门禁详情',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: false,
    },
    {
      id: 'fldcheck_time',
      name: '检查时间',
      type: 5,
      bizType: 'DateTime',
      readable: true,
      writeable: false,
    },
  ],
  lifecycle: [
    {
      id: 'fldevt_id',
      name: 'evt_id',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: false,
    },
    {
      id: 'fldstage',
      name: '阶段',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: false,
    },
    {
      id: 'fldoperator',
      name: '操作人',
      type: 11,
      bizType: 'User',
      readable: true,
      writeable: false,
    },
    {
      id: 'fldoperate_time',
      name: '操作时间',
      type: 5,
      bizType: 'DateTime',
      readable: true,
      writeable: false,
    },
    {
      id: 'fldoperate_desc',
      name: '操作说明',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: false,
    },
  ],
  queryLibrary: [
    {
      id: 'fldiip9LOb',
      name: 'evt_id',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldj5CLc45',
      name: '事件中文名',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldTSdbmKN',
      name: '端',
      type: 4,
      bizType: 'MultiSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'flddrBritu',
      name: '上线版本',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldg957pyK',
      name: '状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldCDvXn26',
      name: '生命周期状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldrVQ43vR',
      name: '参数明细入口',
      type: 15,
      bizType: 'Url',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld3cwv8gv',
      name: '事件定义',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldxv7oxpP',
      name: '触发时机',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldqQfTT9q',
      name: '指标/使用场景',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld5xpsf0p',
      name: '关联参数明细（系统）',
      type: 18,
      bizType: 'DuplexLink',
      readable: true,
      writeable: false,
    },
  ],
  officialParamDetail: [
    {
      id: 'fldtFp6e6R',
      name: '参数主键',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldqb4DXxe',
      name: 'evt_id',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldtskLUgZ',
      name: '事件中文名',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldGR82Uyd',
      name: '参数名',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldebyahiu',
      name: '数据类型',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldByxcM6m',
      name: '必传规则',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldlND5ybE',
      name: '条件说明',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldgqvyWeM',
      name: '枚举/取值范围',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldHjTCw8a',
      name: '参数定义',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldqF9Cbi4',
      name: '版本',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldatGNQbn',
      name: '参数状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldoU3JHCP',
      name: '事件状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldmlfLNtj',
      name: '来源表',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldtVORQx7',
      name: '关联事件',
      type: 18,
      bizType: 'DuplexLink',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldBmL56Ol',
      name: 'App适用性',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldlvMaPTZ',
      name: '备注',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld9bQ8acZ',
      name: '创建时间',
      type: 1001,
      bizType: 'CreatedTime',
      readable: true,
      writeable: false,
    },
    {
      id: 'fldb4sE01c',
      name: '更新时间',
      type: 1002,
      bizType: 'ModifiedTime',
      readable: true,
      writeable: false,
    },
  ],
  webWorkbench: [
    {
      id: 'fldsrxaEFF',
      name: 'evt_id',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldUCSjKe9',
      name: '事件中文名',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'flda01x39h',
      name: '流程阶段',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldvW2Mwmt',
      name: '优先级',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldDE3SD4L',
      name: '端',
      type: 4,
      bizType: 'MultiSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld3VkDsty',
      name: '需求提出人',
      type: 11,
      bizType: 'User',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldmXg85mP',
      name: '需求录入人',
      type: 11,
      bizType: 'User',
      readable: true,
      writeable: true,
    },
    {
      id: 'flddP9xaKr',
      name: '数据负责人',
      type: 11,
      bizType: 'User',
      readable: true,
      writeable: true,
    },
    {
      id: 'flduVUwRRe',
      name: '研发负责人',
      type: 11,
      bizType: 'User',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldy1MVSYO',
      name: 'DS验收人',
      type: 11,
      bizType: 'User',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld1Idvjsh',
      name: '创建时间',
      type: 1001,
      bizType: 'CreatedTime',
      readable: true,
      writeable: false,
    },
    {
      id: 'fldqOMbbdw',
      name: '评审状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldRUa4hOE',
      name: '埋点开发状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldBEJ4bPe',
      name: 'DS验收状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldWc2ndH9',
      name: 'DS验收证据',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldb2kDxmo',
      name: 'DS验收时间',
      type: 5,
      bizType: 'DateTime',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldvE12B7Q',
      name: '发布状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldlZtkX1F',
      name: '发布错误',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'flddzY8JU3',
      name: '发布门禁状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldhtsSfX3',
      name: '发布时间',
      type: 5,
      bizType: 'DateTime',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldUp9uyOX',
      name: '版本',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldWEscUBI',
      name: '最低版本',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld2CdL7yh',
      name: '记录类型',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldS1hupWM',
      name: '变更类型',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldJdHUCCZ',
      name: '处理方',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld840ujbb',
      name: '需求背景',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldhGa3ry1',
      name: '事件定义',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld6EFFRiW',
      name: '触发时机',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldhJiDfHu',
      name: 'UI图',
      type: 17,
      bizType: 'Attachment',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld4AVmBKx',
      name: '指标/使用场景',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldMlUIhg9',
      name: '公共属性要求',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld3tWUeqF',
      name: '需求链接',
      type: 15,
      bizType: 'Url',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldrV4iCGt',
      name: '参数明细入口',
      type: 15,
      bizType: 'Url',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldMPppwVN',
      name: '参数拆行状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldgyxhfbq',
      name: '评审意见',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldEcYYBzj',
      name: '发布门禁失败原因',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldayFBZFq',
      name: '正式状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'flduQb8f0G',
      name: '上线监控状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldj7cAR2N',
      name: '上线监控结论',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldks1ggnG',
      name: '稳定归档时间',
      type: 5,
      bizType: 'DateTime',
      readable: true,
      writeable: true,
    },
  ],
  webParamDetail: [
    {
      id: 'fldZ5kcKld',
      name: '设计参数主键',
      type: 20,
      bizType: 'Formula',
      readable: true,
      writeable: false,
    },
    {
      id: 'fldWR3XMpR',
      name: 'evt_id',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldKMQGhZb',
      name: '参数名',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldYikrhVb',
      name: '数据类型',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldLgmr3Fs',
      name: '必传规则',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldJcTZyE5',
      name: '条件说明',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldztDDZ4W',
      name: '枚举/取值范围',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldK4NfHfC',
      name: '参数定义',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldSheG80P',
      name: '默认值/示例',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldtJMMilx',
      name: 'Web适用性',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldZyCy2Iv',
      name: '参数状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldJtB34PK',
      name: '版本',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldepHtsWx',
      name: '变更类型',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldGIZOLH4',
      name: '来源设计记录ID',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldGAMGK6Q',
      name: '关联设计',
      type: 18,
      bizType: 'DuplexLink',
      readable: true,
      writeable: true,
    },
  ],
  webQueryLibrary: [
    {
      id: 'fldiip9LOb',
      name: 'evt_id',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldj5CLc45',
      name: '事件中文名',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldTSdbmKN',
      name: '端',
      type: 4,
      bizType: 'MultiSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'flddrBritu',
      name: '上线版本',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldg957pyK',
      name: '状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldCDvXn26',
      name: '生命周期状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldrVQ43vR',
      name: '参数明细入口',
      type: 15,
      bizType: 'Url',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld3cwv8gv',
      name: '事件定义',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldxv7oxpP',
      name: '触发时机',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldqQfTT9q',
      name: '指标/使用场景',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld5xpsf0p',
      name: '关联参数明细（系统）',
      type: 18,
      bizType: 'DuplexLink',
      readable: true,
      writeable: false,
    },
  ],
  webOfficialParamDetail: [
    {
      id: 'fldtFp6e6R',
      name: '参数主键',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldqb4DXxe',
      name: 'evt_id',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldtskLUgZ',
      name: '事件中文名',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldGR82Uyd',
      name: '参数名',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldebyahiu',
      name: '数据类型',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldByxcM6m',
      name: '必传规则',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldlND5ybE',
      name: '条件说明',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldgqvyWeM',
      name: '枚举/取值范围',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldHjTCw8a',
      name: '参数定义',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldqF9Cbi4',
      name: '版本',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldatGNQbn',
      name: '参数状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldoU3JHCP',
      name: '事件状态',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldmlfLNtj',
      name: '来源表',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldtVORQx7',
      name: '关联事件',
      type: 18,
      bizType: 'DuplexLink',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldBmL56Ol',
      name: 'Web适用性',
      type: 3,
      bizType: 'SingleSelect',
      readable: true,
      writeable: true,
    },
    {
      id: 'fldlvMaPTZ',
      name: '备注',
      type: 1,
      bizType: 'Text',
      readable: true,
      writeable: true,
    },
    {
      id: 'fld9bQ8acZ',
      name: '创建时间',
      type: 1001,
      bizType: 'CreatedTime',
      readable: true,
      writeable: false,
    },
    {
      id: 'fldb4sE01c',
      name: '更新时间',
      type: 1002,
      bizType: 'ModifiedTime',
      readable: true,
      writeable: false,
    },
  ],
};

// Base 真实枚举值 → UI 业务节点映射
export const STAGE_UI_MAP: Record<string, string> = {
  需求录入: '埋点提需',
  埋点设计: '埋点设计',
  评审通过: '埋点开发',
  埋点开发: '埋点开发',
  数据验收: '埋点校验',
  上线监控: '埋点上线',
  稳定归档: '归档',
  已废弃: '归档',
};

// UI 业务节点 → Base 真实枚举值（写回时用）
export const STAGE_BASE_MAP: Record<string, string> = {
  埋点提需: '需求录入',
  埋点设计: '埋点设计',
  埋点评审: '埋点设计',
  埋点开发: '埋点开发',
  埋点校验: '数据验收',
  埋点上线: '上线监控',
  归档: '稳定归档',
};

// 流程阶段顺序（用于合法性校验，Base 真实枚举顺序）
export const STAGE_ORDER = ['需求录入', '埋点设计', '评审通过', '埋点开发', '数据验收', '上线监控', '稳定归档', '已废弃'];

// 7 个 UI 业务节点顺序
export const UI_STAGE_NODES = ['埋点提需', '埋点设计', '埋点评审', '埋点开发', '埋点校验', '埋点上线', '归档'];

// 优先级排序权重
export const PRIORITY_WEIGHT: Record<string, number> = {
  P0: 0,
  P1: 1,
  P2: 2,
  P3: 3,
};
